//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBtoCSV
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tabela1
    {
        public long id { get; set; }
        public string nazivProj { get; set; }
        public System.DateTime datumVremeProj { get; set; }
        public string sala { get; set; }
        public int trajanje { get; set; }

        public override string ToString()
        {
            return id.ToString() + "," + nazivProj + "," + datumVremeProj.ToString() + "," + sala + "," + trajanje.ToString();
        }
    }
}
